### ISSUE TITLE
duplicate childe view

### ISSUE THREAD

**Issue by ebasahel** [idunnololz/AnimatedExpandableListView#56]
Thanks for sharing this customised expandable list view with us,

I have only one child for each group and I followed the instructions to add the animation to my custom animated expandable list view, but the child of each group is duplicated I don't know why?

I also tried this solution but nothing has changed 
https://github.com/idunnololz/AnimatedExpandableListView/issues/28

**Comment by ebasahel** [comment]
Solved!
I wanted to delete the issue but I can't find a way to delete it.

**Comment by LightWeng** [comment]
Hi,ebasahel,I met the same issue as yours,but I can't resolve it by myself,could you please help me out?Thank you a lot.
